# Generated by Django 5.2.15 on 2026-07-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='creator_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller')], default='seller', max_length=20, null=True),
        ),
    ]
