# Generated by Django 5.2.15 on 2026-07-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0002_deal_creator_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
