# Generated by Django 5.2.15 on 2026-07-19 11:12

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0003_deal_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='deal.deal')),
            ],
        ),
    ]
