# Generated by Django 5.2.15 on 2026-07-24 08:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deal', '0004_dealimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='color',
            field=models.CharField(blank=True, default='#F8F9FA', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color (e.g. #F8F9FA).', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
