# Generated by Django 5.2.15 on 2026-06-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
