# Generated by Django 5.2.15 on 2026-07-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('new_product', 'New Product'), ('new_deal', 'New Deal'), ('new_collection', 'New Collection'), ('new_brand', 'New Brand'), ('new_message', 'New Message'), ('order_created', 'Order Created'), ('order_confirmed', 'Order Confirmed'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('payment_refunded', 'Payment Refunded'), ('wishlist_price_drop', 'Wishlist Price Drop'), ('wishlist_back_in_stock', 'Wishlist Back In Stock'), ('system', 'System')], default='system', max_length=40, null=True),
        ),
    ]
