# Generated by Django 5.2.15 on 2026-07-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorder',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'user__role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, to='account.account'),
        ),
    ]
