# Generated by Django 5.2.15 on 2026-08-02 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderitem_price_orderitem_discount_amount_and_more'),
        ('product', '0006_product_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='product.product'),
        ),
    ]
