# Generated by Django 5.2.15 on 2026-08-02 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_profile_picture'),
        ('order', '0004_alter_orderitem_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerorder',
            name='seller',
            field=models.ForeignKey(limit_choices_to={'user__role': 'seller'}, on_delete=django.db.models.deletion.CASCADE, related_name='seller_orders', to='account.account'),
        ),
    ]
